---
# playbook to install docker on the remote host
# references
#            : http://www.inanzzz.com/index.php/post/lvwk/installing-docker-and-docker-compose-on-remote-server-with-ansible
#            : https://docs.ansible.com/ansible/latest/modules/apt_module.html
#            : https://docs.docker.com/install/linux/docker-ce/ubuntu/

# Playbook for DevOps project
# 1. Install Docker
# 2. Install Open JDK


##################################### Install Docker ##########################################

# Update the basic packages
- hosts: TestServer
  become_user: root
  tasks:
  - name: install basic software
    apt:
      name: ['apt-transport-https','ca-certificates','curl','gnupg-agent' ,'software-properties-common']
      force: yes
      force_apt_get: true
      install_recommends: yes
      state: present
      update_cache: yes
    tags:
      - docker

  # Add the GPG key (curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -)
  - name: add GPG key for docker
    apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg
    tags:
      - docker

  #add the docker repo sudo add-apt-repository deb  https://download.docker.com/linux/ubuntu xenial stable
  - name: Set up stable repository
    apt_repository:
      repo: deb https://download.docker.com/linux/ubuntu xenial stable
      state: present
    tags:
      - docker

  # Update the apt package index
  - name: update the apt package index
    apt:
  
  # install docker
  - name: install docker
    apt:
      name: docker-ce
      state: present
      update_cache: yes
    tags:
      -docker
  ################################## Install Open JDK ################################################
  # Install open JDK apt-get install -y openjdk-8-jd
  - name: Install JDK
    apt:
      name: openjdk-8-jdk
      state: present
    tags:
      -OpenJDK